- hosts: localhost
  become: true
  tasks:
    - name: Install zsh
      kewlfft.aur.aur:
        use: yay
        name:
        - pulseaudio-ctl 

# - name: Install package_name_1 and package_name_2 using yay
#   kewlfft.aur.aur:
#     use: yay
#     name:
#       - package_name_1
#       - package_name_2
