- name: add 'aur_builder to sudoers'
  hosts: localhost
  become: true
  ansible.builtin.linefile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'
