- name: add 'aur_builder to sudoers'
  hosts: localhost
  become: true
  tasks:
    ansible.builtin.linefile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'
