- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update pacman
    become: true
    pacman:
      update_cache: true
      upgrade: yes
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/arch-keyring.yml
    - include: tasks/zsh.yml
    - include: tasks/doas.yml
    - include: tasks/core.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/sudo.yml
    - include: tasks/git-remote.yml
    - include: tasks/clones.yml
    - include: tasks/suckless.yml
    - include: tasks/curls.yml
    - include: tasks/system.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/aurpacks.yml
    - include: tasks/remove-sudo.yml
    - include: tasks/final-cleanup.yml

