- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update pacman
    become: true
    pacman:
      update_cache: true
      upgrade: yes
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/dirs.yml
    # - include: tasks/group.yml
    - include: tasks/sudo.yml
    - include: tasks/arch-keyring.yml
    - include: tasks/zsh.yml
    - include: tasks/doas.yml
    - include: tasks/rustup.yml
    - include: tasks/core.yml
    - include: tasks/aur.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/policykit.yml
    - include: tasks/aurpacks.yml
    - include: tasks/clones.yml
    - include: tasks/suckless.yml
    - include: tasks/nvm.yml
    # - include: tasks/gnupg.yml
    - include: tasks/starship.yml
    - include: tasks/moz.yml
    - include: tasks/nix.yml
    - include: tasks/cargo.yml
    - include: tasks/hugo.yml
    - include: tasks/cronie.yml
    - include: tasks/cron.yml
    - include: tasks/root-bash.yml
    # - include: tasks/productivity-tools.yml
    - include: tasks/remove-nano.yml
    - include: tasks/remove-sudo.yml


