
# ---
#   - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
#     hosts: localhost
#     become: true
#     tasks:
#       - name: user example present
#         ansible.builtin.user:
#           name: johnd
#           password: "{{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
#           groups:
#             - wheel
#             - adm
#           state: "present"
#           shell: "/bin/bash"
#           createhome: true
#           home: "/home/johnd"
#           comment: "ansible example"
      
      

---
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    hosts: localhost
    become: true
    tasks:
      - name: Create the aur_builder user
        ansible.builtin.user:
          name: aur_builder
          groups:
            - wheel
          createhome: true

      - name:
        # become: true
        ansible.builtin.linefile:
          path: /etc/sudoers.d/11-install-aur_builder
          line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
          create: yes
          validate: 'visudo -cf %s'
      
      

      # - name: Create the aur_builder user
      #     ansible.builtin.linefile:
      #       path: /etc/sudoers.d/11-install-aur_builder
      #       line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      #       create: yes
      #       validate: 'visudo -cf %s'
