- name: autocpufreq
  ansible.builtin.git:
    repo: 'https://github.com/AdnanHodzic/auto-cpufreq.git'
    dest: "{{ lookup('env', 'HOME') }}/dl/git-clones/auto-cpufreq"
  tags:
    - install
    - dotfiles
    - gits
- name: clipmenu
  ansible.builtin.git:
    repo: 'https://github.com/cdown/clipmenu.git' 
    dest: "{{ lookup('env', 'HOME') }}/dl/git-clones/clipmenu"
  tags:
    - install
    - dotfiles
    - gits
- name: Run clipmenu
  become: true
  shell: cd /home/chris/dl/git-clones/clipmenu/ && make install
  tags:
    - install
    - dotfiles
    - gits

