- name: clipmenu
  ansible.builtin.git:
    repo: 'https://github.com/cdown/clipmenu.git' 
    dest: "{{ lookup('env', 'HOME') }}/dl/git-clones/clipmenu"
  tags:
    - install
    - dotfiles
    - gits
- name: Run clipmenu
  become: true
  shell: cd /home/chris/dl/git-clones/clipmenu/ && make install
  tags:
    - install
    - dotfiles
    - gits
- name: Clone tmux tpm
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm.git' 
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux/plugins/tpm"
  tags:
    - install
    - dotfiles
    - gits
- name: Clone swiv
  ansible.builtin.git:
    repo: 'https://github.com/ShaqeelAhmad/swiv.git' 
    dest: "{{ lookup('env', 'HOME') }}/dl/git-clones/swiv"
  tags:
    - install
    - dotfiles
    - gits
- name: Clone evremaps
  ansible.builtin.git:
    repo: 'https://github.com/wez/evremap.git'
    dest: "{{ lookup('env', 'HOME') }}/dl/git-clones/evremap"
  tags:
    - install
    - dotfiles
    - gits
- name: Build evremaps
  shell: cd /home/chris/dl/git-clones/evremap/ && cargo build --release
  tags:
    - install
    - dotfiles
    - gits
- name: Move evremaps
  become: true
  shell: cd /home/chris/dl/git-clones/evremap/ && cp /home/chris/dl/git-clones/evremap/target/release/evremap /usr/local/bin/evremap
  tags:
    - install
    - dotfiles
    - gits
