
- name: Install System Packages 1 
  become: true
  pacman:
    name: ["alacritty", "arch-wiki-docs", "aspell-en", "atuin", "bat", "barrier", "bluez", "bluez-utils", "brightnessctl", "broot", "calcurse", "calibre", "clipnotify", "codespell", "cronie", "ctags", "cups", "cutefish-icons", "discord", "dog", "dunst", "ebook-tools", "entr", "exa", "fd", "firefox", "fisher", "flake8", "fontconfig", "ffmpeg", "fzf", "gimp", "gimp-plugin-gmic", "glow", "gnucash", "go", "gparted", "grub-btrfs"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 
  become: true
  pacman:
    name: [ "gufw", "harfbuzz", "inkscape", "iperf", "languagetool", "libmythes", "libreoffice-fresh", "libsecret", "libnotify", "luacheck", "lxappearance", "lynx", "maim",  "man-db", "moreutils", "mpc", "mpd", "mpv", "mtr", "mythes-en", "navi", "ncdu", "ncmpcpp", "net-tools", "newsboat", "noto-fonts", "noto-fonts-emoji", "okular", "pandoc-cli", "pass-otp",  "pcmanfm", "picom", "pipewire-pulse", "polkit", "procs", "pulsemixer", "pydf", "python-black", "python-netaddr", "python-pynvim"]
  tags:
    - install
    - neovim
    - core

- name: Remove pipewire-media-sessioin 
  become: true
  pacman:
    name: ["pipewire-media-session"]
    state: absent
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 
  become: true
  pacman:
    name: [ "r", "redshift", "ripgrep", "rmlint", "rofi", "sdcv", "shellcheck", "shfmt", "socat", "stylua", "sxhkd", "sxiv", "syncthing", "task", "the_silver_searcher", "timew", "tk", "tldr", "tmux", "transmission-cli", "tree", "unclutter", "unzip", "ueberzug", "urlscan", "vim", "vit", "wireguard-tools", "wireplumber", "xcape", "xdotool", "xclip", "xkeycaps", "xorg-server", "xorg-xinit", "xorg-xwininfo", "xorg-xprop", "xorg-xev", "xorg-xset", "xorg-xsetroot", "xsel", "xwallpaper", "yt-dlp", "yubikey-manager", "zathura", "zathura-pdf-mupdf", "zk", "zoxide", "zbar" ]
  tags:
    - install
    - neovim
    - core
