
- name: Install System Packages 1 
  become: true
  pacman:
    name: ["alacritty", "arch-wiki-docs", "aspell-en", "atuin", "bat", "barrier", "bluez", "bluez-openrc", "bluez-utils", "brightnessctl", "broot", "calibre", "clipnotify", "codespell", "ctags", "cutefish-icons", "discord", "dog", "dunst", "ebook-tools", "entr", "exa", "fd", "firefox", "flake8", "fontconfig", "ffmpeg", "fuse2", "fuse3", "fzf", "gimp", "gimp-plugin-gmic", "glow", "gnucash", "go"]
  tags:
    - install
    - neovim
    - core

- name: Remove pipewire-media-sessioin 
  become: true
  pacman:
    name: ["pipewire-pulse", "pipewire-media-session"]
    state: absent
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 
  become: true
  pacman:
    name: ["keepassxc", "harfbuzz", "inkscape", "languagetool", "libmythes", "libreoffice-fresh", "libsecret", "libnotify", "lxappearance", "lynx", "maim",  "man-db", "moreutils", "mpc", "mpd", "mpv", "mtr", "mythes-en", "navi", "ncdu", "ncmpcpp", "net-tools", "newsboat", "noto-fonts", "noto-fonts-emoji", "okular", "pam-u2f",  "pandoc-cli", "pavucontrol", "pass-otp", "pcmanfm", "pipewire", "wireplumber", "pipewire-alsa", "pipewire-pulse", "polkit",  "pulsemixer", "pydf", "python-black", "python-netaddr", "python-pynvim"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 
  become: true
  pacman:
    name: ["redshift", "rclone", "ripgrep", "rofi", "sdcv", "shellcheck", "shfmt", "socat", "stylua", "sxiv", "syncthing", "task", "the_silver_searcher", "timew", "tk", "tldr", "tmux", "transmission-cli", "tree", "unclutter", "unzip", "ueberzug", "urlscan", "vim", "vit", "wireguard-tools", "xcape", "xdotool", "xorg-xdpyinfo",  "xclip", "xkeycaps", "xorg-server", "xorg-xinput",  "xorg-server-xephyr", "xorg-xinit", "xorg-xwininfo", "xorg-xprop", "xorg-xev", "xorg-xset", "xorg-xsetroot", "xsel", "xwallpaper", "yt-dlp", "yubikey-manager", "zathura", "zathura-pdf-mupdf", "zk", "zoxide", "zbar" ]
  tags:
    - install
    - neovim
    - core
