- name: Install System Packages 1 
  become: true
  pacman:
    name: ["alacritty", "arch-wiki-docs", "aspell-en", "atuin", "bat", "brightnessctl", "broot", "calcurse", "calibre", "clipnotify", "codespell", "cronie", "ctags", "cups", "cutefish-icons", "discord", "dog", "dunst", "ebook-tools", "entr", "exa", "fd", "firefox", "fisher", "flake8", "fontconfig", "fzf", "gimp", "gimp-plugin-gmic", "glow", "gnome-keyring", "gnucash", "go", "gparted", "grub-btrfs"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 
  become: true
  pacman:
    name: [ "gufw", "harfbuzz", "inkscape", "iperf", "languagetool", "lazygit", "libmythes", "libreoffice-fresh", "libsecret", "luacheck", "lxappearance", "lynx", "maim", "moreutils", "mpc", "mpd", "mpv", "mtr", "mythes-en", "navi", "ncdu", "ncmpcpp", "net-tools", "newsboat", "okular", "pandoc-cli", "paru", "pcmanfm", "picom", "procs", "pulsemixer", "pydf", "python-black", "python-netaddr", "python-pynvim"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 
  become: true
  pacman:
    name: [ "r", "redshift", "ripgrep", "rmlint", "rofi", "sdcv", "shellcheck", "shfmt", "socat", "stylua", "sxhkd", "sxiv", "syncthing", "texlive-most", "the_silver_searcher", "tk", "tldr", "tmux", "transmission-cli", "tree", "unclutter", "urlscan", "vim", "wireguard-tools", "xcape", "xkeycaps", "xorg-xev", "xorg-xset", "xorg-xsetroot", "xsel", "xwallpaper", "zathura", "zk", "zoxide", ]
  tags:
    - install
    - neovim
    - core
