- name: Install System Packages 1 
  become: true
  pacman:
    name: ["arch-wiki-docs", "aspell-en", "bat", "brightnessctl", "calcurse", "calibre", "clipnotify", "codespell", "cronie", "ctags","cups", "cutefish-icons", "discord", "dunst", "ebook-tools", "entr", "exa", "fd", "firefox", "fisher", "flake8", "fzf", "gimp", "gimp-plugin-gmic", "glow", "gnome-keyring", "gnucash", "go", "gparted", "grub-btrfs"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 
  become: true
  pacman:
    name: [ "gufw", "inkscape", "iperf", "languagetool", "lazygit", "libmythes", "libreoffice-fresh", "libsecret", "luacheck", "lxappearance", "lynx", "maim", "moreutils", "mpc", "mpd", "mpv", "mtr", "mythes-en", "ncdu", "ncmpcpp", "net-tools", "newsboat", "okular", "pandoc-cli", "paru", "pcmanfm", "procs", "pulsemixer", "pydf", "python-black", "python-netaddr", "python-pynvim"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 
  become: true
  pacman:
    name: [ "r", "redshift", "ripgrep", "rmlint", "rofi", "sdcv", "shellcheck", "shfmt", "sxhkd", "sxiv", "syncthing", "texlive-most", "the_silver_searcher", "tk", "tldr", "transmission-cli", "tree", "unclutter", "urlscan", "vim", "wireguard-tools", "xcape", "xclip", "xkeycaps", "xorg-xev", "xorg-xset", "xorg-xsetroot", "xsel", "xwallpaper", "zathura", "zk", "zoxide", ]
  tags:
    - install
    - neovim
    - core
