- name: Installing stow
  become: true
  pacman: 
    name: stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@gitlab.com:chris-m/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/repos/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/repos/dotfiles && ./arch
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning privatefiles
  ansible.builtin.git:
    repo: 'git@gitlab.com:chris-m/privatefiles.git'
    dest: "{{ lookup('env', 'HOME') }}/repos/privatefiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/repos/privatefiles && ./pri
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning newsboat
  ansible.builtin.git:
    repo: 'git@gitlab.com:chris-m/newsboat-repo.git'
    dest: "{{ lookup('env', 'HOME') }}/repos/newsboat-repo"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/repos/newsboat-repo && ./news
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning fish history
  ansible.builtin.git:
    repo: 'git@github.com:cmpi66/fish-history-arch.git'
    dest: "{{ lookup('env', 'HOME') }}/repos/fish-history-arch"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/repos && stow --target=/home/chris fish-history-arch
  tags:
    - install
    - dotfiles
    - stow
