- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/cmpi66/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/repos/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: gentoo
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: ./arch
  tags:
    - install
    - dotfiles
    - stow
