- name: Clean up extra dirs and files
  shell: cd ~/repos/dotfiles/ && ./removefiles 
  tags:
  - install
  - cleanup
- name: Move npm
  shell: cd ~/repos/dotfiles/ && ./mvnpm
  tags:
  - install
  - cleanup
- name: Remove default dirs and create new dirs
  shell: "cd ~/repos/dotfiles/ && ./newdirs"
  tags:
    - install
    - dirs
    - cleanup
