- name: Clean up extra dirs and files
  shell: cd ~/repos/dotfiles/ && ./removefiles 
  tags:
  - install
  - cleanup
- name: Move npmrc
  shell: cd ~/repos/dotfiles/ && ./mvnpm
  tags:
  - install
  - cleanup
- name: Remove default dirs and create new dirs
  shell: "cd ~/repos/dotfiles/ && ./newdirs"
  tags:
    - install
    - dirs
    - cleanup
- name: Run gpg cmd so dir can be created 
  shell: "gpg --list-keys"
  tags:
    - install
    - gnupg
- name: Move gnupg dir 
  shell: "mv ~/.gnupg/ ~/.local/share/gnupg"
  tags:
    - install
    - gnupg
    - cleanup
