# - name: Clean up extra dirs and files
#   shell:  ./removefiles 
#   tags:
#   - install
#   - cleanup
- name: Remove default dirs and create new dirs
  shell: "./newdirs"
  tags:
    - install
    - dirs
    - cleanup
- name: Run gpg cmd so dir can be created 
  shell: "gpg --list-keys"
  tags:
    - install
    - gnupg
- name: Move npmrc and gnupgdir
  shell: ./mvnpm
  tags:
  - install
  - cleanup
# - name: Move gnupg dir and  
#   shell: "mv ~/.gnupg/ ~/.local/share/gnupg"
#   tags:
#     - install
#     - gnupg
#     - cleanup
