#!/bin/sh

## Got this function from LUKE'S LARBS
refreshkeys() { \
	case "$(readlink -f /sbin/init)" in
		*systemd* )
			pacman --noconfirm -S archlinux-keyring polkit >/dev/null 2>&1
			;;
		*)
			if ! grep -q "^\[universe\]" /etc/pacman.conf; then
				echo "[universe]
Server = https://universe.artixlinux.org/\$arch
Server = https://mirror1.artixlinux.org/universe/\$arch
Server = https://mirror.pascalpuffke.de/artix-universe/\$arch
Server = https://artixlinux.qontinuum.space/artixlinux/universe/os/\$arch
Server = https://mirror1.cl.netactuate.com/artix/universe/\$arch
Server = https://ftp.crifo.org/artix-universe/" >> /etc/pacman.conf
				pacman -Sy
			fi
			pacman --noconfirm --needed -S artix-keyring artix-archlinux-support >/dev/null 2>&1
			for repo in extra community; do
				grep -q "^\[$repo\]" /etc/pacman.conf ||
					echo "[$repo]
Include = /etc/pacman.d/mirrorlist-arch" >> /etc/pacman.conf
			done
			pacman -Sy >/dev/null 2>&1
			pacman-key --populate archlinux >/dev/null 2>&1
			;;
	esac ;}


refreshkeys || error "Error automatically refreshing Arch keyring. Consider doing so manually."
