- name: Build lunarvim 
  shell: LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh) --yes
  tags:
    - install
    - lvim
- name: Delete default lvim and stow lvim config
  shell: rm -rf ~/.config/lvim/ && cd ~/repos/dotfiles/ && stow --target=/home/chris lvim
  tags:
    - install
    - lvim
