
- name: Build nix 
  shell: curl -L https://nixos.org/nix/install | sh
  tags:
    - install
    - nix
- name: Enable experimental flakes
  shell: mkdir ~/.config/nix && echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
  tags:
    - install
    - nix
- name: Source nix
  shell: . /home/chris/.nix-profile/etc/profile.d/nix.sh
  tags:
    - install
    - nix
- name: Install ema note
  shell: cd ~/repos/dotfiles/ && ./ema
  tags:
    - install
    - nix
