- name: Pull nvm command
  shell: "mkdir ~/.config/nvm && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | NVM_DIR='/home/chris/.config/nvm' bash"
  tags:
    - install
    - nvm
- name: Run nvm command
  shell: cd $HOME/repos/dotfiles && ./nod
  tags:
    - install
    - nvm
- name: Run nvm command
  shell: npm i -g neovim
  tags:
    - install
    - nvm
