- hosts: localhost
  tasks: 
  - name: Cloning privatefiles
    ansible.builtin.git:
      repo: 'git@gitlab.com:chris-m/privatefiles.git'
      dest: "{{ lookup('env', 'HOME') }}/repos/privatefiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: master
    tags:
      - install
      - privatefiles
      - stow
  - name: Stow privatefiles
    shell: cd $HOME/repos/privatefiles && stow --target=/home/chris */
    tags:
      - install
      - privatefiles
      - stow

  - name: Cloning newsboat
    ansible.builtin.git:
      repo: 'git@gitlab.com:chris-m/newsboat-gentoo.git'
      dest: "{{ lookup('env', 'HOME') }}/repos/newsboat-gentoo"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: master
    tags:
      - install
      - privatefiles
      - stow
  - name: Stow newsboat
    shell: cd $HOME/repos/newsboat-gentoo && stow --target=/home/chris newsboat
    tags:
      - install
      - privatefiles
      - stow

  - name: Cloning fish history
    ansible.builtin.git:
      repo: 'git@github.com:cmpi66/fish-history-gentoo.git'
      dest: "{{ lookup('env', 'HOME') }}/repos/fish-history-gentoo"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: main
    tags:
      - install
      - privatefiles
      - stow
  - name: Stow fish history
    shell: cd $HOME/repos && stow --target=/home/chris fish-history-gentoo
    tags:
      - install
      - privatefiles
      - stow

  - name: add remote dotfiles
    shell: cd $HOME/repos/dotfiles && git remote rm origin && git remote add origin git@gitlab.com:chris-m/dotfiles.git && git remote set-url --add origin git@github.com:cmpi66/dotfiles.git 
    tags:
      - install
      - privatefiles
      - remote

  - name: add remote privatefiles
    shell: cd $HOME/repos/privatefiles && git remote rm origin && git remote add origin git@gitlab.com:chris-m/privatefiles.git && git remote set-url --add origin git@github.com:cmpi66/privatefiles.git 
    tags:
      - install
      - privatefiles
      - remote

  - name: add remote newsboat
    shell: cd $HOME/repos/newsboat-gentoo && git remote rm origin && git remote add origin git@gitlab.com:chris-m/newsboat-gentoo.git && git remote set-url --add origin git@github.com:cmpi66/newsboat-gentoo.git 
    tags:
      - install
      - privatefiles
      - remote
  - name: add remote ansible-bootstrap
    shell: cd $HOME/ansible-bootstrap && git remote rm origin && git remote add origin git@gitlab.com:chris-m/ansible-bootstrap.git && git remote set-url --add origin git@github.com:cmpi66/ansible-bootstrap.git 
    tags:
      - install
      - privatefiles
      - remote
  - name: add remote fish-history-gentoo
    shell: cd $HOME/repos/fish-history-gentoo && git remote rm origin && git remote add origin git@gitlab.com:chris-m/fish-history-gentoo.git && git remote set-url --add origin git@github.com:cmpi66/fish-history-gentoo.git 
    tags:
      - install
      - privatefiles
      - remote
