- name: Build rustup 
  shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  tags:
    - install
    - rust
- name: mv .cargo
  shell: "mv ~/.cargo ~/.local/share/cargo"
  tags:
    - install
    - rust
- name: mv .rustup
  shell: "mv ~/.rustup ~/.local/share/rustup && zsh"
  tags:
    - install
    - rust
