# - name: Build suckless st
#   become: true
#   shell: "cd {{ lookup('env', 'HOME') }}/.config/suckless/st && make install"
#   tags:
#     - install
#     - suckless
- name: Build suckless dwm
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/.config/suckless/dwm && make install"
  tags:
    - install
    - suckless
- name: Build suckless dmenu
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/.config/suckless/dmenu && make install"
  tags:
    - install
    - suckless
- name: Build suckless slstatus
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/.config/suckless/slstatus && rm config.h && make install"
  tags:
    - install
    - suckless
