- name: add wheel perms to build aur packages without pass prompt
  become: true
  shell: "cp /home/chris/repos/dotfiles/sudoers/00-aur-no-sudo /etc/sudoers.d/"
  tags:
    - install
    - sudo
- name: increase makepkg cores for compilation
  become: true
  shell: sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf 
  tags:
    - install
    - sudo
