- name: Update policy kit rules
  become: true
  shell: "cd /home/chris/repos/dotfiles/polkit && cp 49-nopasswd_global.rules /etc/polkit-1/rules.d/"
  tags:
    - install
    - polkit
    - system
- name: Remove nano 
  become: true
  pacman:
    name: ["nano", "nano-syntax-highlighting"]
    state: absent
  tags:
    - install
    - core
    - nano
    - system
- name: Get root bashrc and export nvim to editor
  become: true
  shell: cp /etc/skel/.bashrc /root/.bashrc && echo "export EDITOR=lvim" >> /root/.bashrc
  tags:
    - install
    - root-bash
    - system
- name: Get root bashrc and export nvim to editor
  become: true
  shell: echo "export VISUAL=lvim" >> /root/.bashrc
  tags:
    - install
    - root-bash
    - system
- name: Get root bashrc and export nvim to editor
  become: true
  shell: echo "alias nvim='lvim'" >> /root/.bashrc
  tags:
    - install
    - root-bash
    - system

- name: Install pacman -Sy crontab
  become: true
  shell: cd /home/chris/repos/dotfiles/ && crontab mycron
  tags:
    - install
    - cron
    - system



# Will have to do these manually
# - name: Enable and start cronie
#   become: true
#   ansible.builtin.service:
#     name: cronie.service
#     enabled: yes
#     state: restarted
#   tags:
#     - install
#     - system
# - name: Enable and start bluetooth
#   become: true
#   ansible.builtin.service:
#     name: bluetooth.service
#     enabled: yes
#     state: restarted
#   tags:
#     - install
#     - system
# - name: Enable and start pcsc
#   become: true
#   ansible.builtin.service:
#     name: pcscd.service
#     enabled: yes
#     state: restarted
#   tags:
#     - install
#     - system
# - name: Enable and start cronie
#   become: true
#   ansible.builtin.systemd:
#     name: cronie.service
#     state: restarted
#     enabled: true
#   tags:
#     - install
#     - sysctl
#     - system

# - name: Enable and start bluetooth
#   become: true
#   ansible.builtin.systemd:
#     name: bluetooth.service
#     state: restarted
#     enabled: true
#   tags:
#     - install
#     - sysctl
#     - system
# - name: Enable and start pcsc
#   become: true
#   ansible.builtin.systemd:
#     name: pcscd.service
#     state: restarted
#     enabled: true
#   tags:
#     - install
#     - sysctl
#     - system
