- name: Install ZSH and fish
  become: true
  pacman: 
    name: ["zsh", "fish"]
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh) $(whoami)
  tags: *tags_for_zsh_tasks

- name: Source zdotdir system wide
  become: true
  shell: "echo 'export ZDOTDIR=$HOME/.config/zsh' >> /etc/zsh/zshenv"
  tags: *tags_for_zsh_tasks
